apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: moodle-base
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: namespaces
  interval: 1m0s
  path: ./moodle/yamls
  prune: true
  sourceRef:
    kind: GitRepository
    name: moodle-ipm
    namespace: tanzu-continuousdelivery-resources
