---
# Source: moodle/templates/externaldb-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "release-name-moodle-externaldb"
  namespace: "moodle"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: moodle
    app.kubernetes.io/version: 4.3.0
    helm.sh/chart: moodle-19.0.0
type: Opaque
data:
  mariadb-password: ""
---
# Source: moodle/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-moodle
  namespace: "moodle"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: moodle
    app.kubernetes.io/version: 4.3.0
    helm.sh/chart: moodle-19.0.0
type: Opaque
data:
  moodle-password: "dzN4QWVDb2tKVg=="
---
# Source: moodle/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: release-name-moodle-moodle
  namespace: "moodle"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: moodle
    app.kubernetes.io/version: 4.3.0
    helm.sh/chart: moodle-19.0.0
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
# Source: moodle/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-moodle
  namespace: "moodle"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: moodle
    app.kubernetes.io/version: 4.3.0
    helm.sh/chart: moodle-19.0.0
spec:
  type: LoadBalancer
  externalTrafficPolicy: "Cluster"
  sessionAffinity: None
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  selector:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/name: moodle
---
# Source: moodle/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-moodle
  namespace: "moodle"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: moodle
    app.kubernetes.io/version: 4.3.0
    helm.sh/chart: moodle-19.0.0
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: moodle
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: moodle
        app.kubernetes.io/version: 4.3.0
        helm.sh/chart: moodle-19.0.0
      annotations:
    spec:
      
      securityContext:
        fsGroup: 1001
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: release-name
                    app.kubernetes.io/name: moodle
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      priorityClassName: ""
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "status.localhost"
      initContainers:
      containers:
        - name: release-name-moodle
          image: docker.io/bitnami/moodle:4.3.0-debian-11-r0
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: APACHE_HTTP_PORT_NUMBER
              value: "8080"
            - name: APACHE_HTTPS_PORT_NUMBER
              value: "8443"
            - name: MOODLE_DATABASE_TYPE
              value: ""
            - name: MOODLE_DATABASE_HOST
              value: ""
            - name: MOODLE_DATABASE_PORT_NUMBER
              value: "3306"
            - name: MOODLE_DATABASE_NAME
              value: "bitnami_moodle"
            - name: MOODLE_DATABASE_USER
              value: "bn_moodle"
            - name: MOODLE_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: release-name-moodle-externaldb
                  key: mariadb-password
            - name: MOODLE_SKIP_BOOTSTRAP
              value: "no"
            - name: MOODLE_USERNAME
              value: "user"
            - name: MOODLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: release-name-moodle
                  key: moodle-password
            - name: MOODLE_EMAIL
              value: "user@example.com"
          envFrom:
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          livenessProbe:
            httpGet:
              path: /login/index.php
              port: http
            initialDelaySeconds: 600
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /login/index.php
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 6
          resources:
            limits: {}
            requests:
              cpu: 300m
              memory: 512Mi
          volumeMounts:
            - name: moodle-data
              mountPath: /bitnami/moodle
              subPath: moodle
            - name: moodle-data
              mountPath: /bitnami/moodledata
              subPath: moodledata
      volumes:
        - name: moodle-data
          persistentVolumeClaim:
            claimName: release-name-moodle-moodle
