apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: wordpress-test
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m0s
  path: ./wordpress
  prune: true
  sourceRef:
    kind: GitRepository
    name: moodle-ipm
    namespace: tanzu-continuousdelivery-resources
