---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: "moodle"
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/version: 8.0.35
type: Opaque
data:
  mysql-password: "WXU2SFhaZUdpdQ=="
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: "moodle"
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 7.2.2
type: Opaque
data:
  redis-password: "SVBNaXBtMTAhCg=="
---
apiVersion: v1
kind: Secret
metadata:
  name: moodle-secret
  namespace: "moodle"
  labels:
    app.kubernetes.io/name: moodle
type: Opaque
data:
  moodle-password: "SVBNaXBtMTAhCg=="
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: system
  namespace: "moodle"
  labels:
    app.kubernetes.io/name: moodle
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
  namespace: "moodle"
  labels:
    app.kubernetes.io/name: moodle
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "50Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: moodle
  namespace: "moodle"
  labels:
    app.kubernetes.io/name: moodle
spec:
  type: LoadBalancer
  externalTrafficPolicy: "Cluster"
  sessionAffinity: None
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  selector:
    app.kubernetes.io/name: moodle
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle
  namespace: "moodle"
  labels:
    app.kubernetes.io/name: moodle
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: moodle
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: moodle
      annotations:
    spec:
      
      securityContext:
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: moodle
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      priorityClassName: ""
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "status.localhost"
      initContainers:
      containers:
        - name: moodle
          image: harbor.cpd.uva.es/moodle/moodle:4.3
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsNonRoot: true
            runAsUser: 1001
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: APACHE_HTTP_PORT_NUMBER
              value: "8080"
            - name: APACHE_HTTPS_PORT_NUMBER
              value: "8443"
            - name: MOODLE_DATABASE_TYPE 
              value: "mysqli"
            - name: MOODLE_DATABASE_HOST
              value: "10.96.140.13"
            - name: MOODLE_DATABASE_PORT_NUMBER
              value: "3306"
            - name: MOODLE_DATABASE_NAME
              value: "my_database"
            - name: MOODLE_DATABASE_USER
              value: "root"
            - name: MOODLE_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: MOODLE_SKIP_BOOTSTRAP
              value: "no"
            - name: MOODLE_USERNAME
              value: "user"
            - name: MOODLE_PASSWORD
              value: "password"
            - name: MOODLE_SITE_NAME
              value: Moodle de Universidad de Valladolid
            - name: MOODLE_LANG
              value: es            
            - name: MOODLE_EMAIL
              value: "user@example.com" 
          envFrom:
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          livenessProbe:
            httpGet:
              path: /login/index.php
              port: http
            initialDelaySeconds: 600
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /login/index.php
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 6
          resources:
            limits: {}
            requests:
              cpu: 300m
              memory: 512Mi
          volumeMounts:
            - name: system
              mountPath: /bitnami/moodle
            - name: data
              mountPath: /bitnami/moodledata
      volumes:
        - name: system
          persistentVolumeClaim:
            claimName: system
        - name: data
          persistentVolumeClaim:
            claimName: data
